add match_regex (optional field) function when doing website-change-v2 of DCV
open-mpic/open-mpic-core-python pull request #15
Opened 2024-12-31 06:56 UTC by whtung

2025-01-03 20:20 UTC, birgelee requested changes
Good overall. Let me know your thoughts on the line comments. Also, this needs testing before merge.

2025-01-03 20:20 UTC, birgelee commented on src/open_mpic_core/mpic_dcv_checker/mpic_dcv_checker.py
> +                    re_result = match.group(1)
@whtung can you explain your thoughts on using re_result = match.group(1) and then comparing re_result to the expected response content? This seems to imply that the first parenthesis grouping in the REGEX must be the expected response content.

My personal intention for the regex behavior was slightly different.

I was going to have if regex is specified, match must be not equal to None. So long as match is not None, and the expected response content was contained in the response, the check would pass.

I would prefer to move to this logic for the regex if you think this would still provide sufficient flexibility to your use case.

2025-01-03 20:20 UTC, birgelee commented on src/open_mpic_core/mpic_dcv_checker/mpic_dcv_checker.py
> +                    dcv_check_response.check_passed = (re_result == expected_response_content)
Personally I think this should be changed to 

check_passed = False

Given the response did not match the regex and the regex string was specified, even if the response matches the expected content I think it should be check_passed = False

2025-01-05 01:34 UTC, whtung commented on src/open_mpic_core/mpic_dcv_checker/mpic_dcv_checker.py
> +                    re_result = match.group(1)
@birgelee Thank you for taking the time to review this PR.

This is indeed the intention I originally imagined for match_regex, but after your explanation, it seems that your logic is actually more suitable. I also think it is also better able to handle various different use cases.

That is, when a match_regex value is specified, directly validate whether the response matches the match_regex, instead of extracting the first parenthesis grouping in the REGEX and then comparing it to the expected content.

2025-01-05 01:34 UTC, whtung commented on src/open_mpic_core/mpic_dcv_checker/mpic_dcv_checker.py
> +                    dcv_check_response.check_passed = (re_result == expected_response_content)
OK. This design is better!! Thank you.

And this is also more in line with the API documentation's description of match_regex.
https://open-mpic.org/documentation.html#/paths/~1mpic/post

2025-01-05 03:44 UTC, sciros commented
Thanks for this submission!
This will need tests added to cover the behavior.
Please add a test in `test_mpic_dcv_checker.py` that specifies that http 01 validation should accept an optional regex to match, and possibly a test to specify that the regex takes priority over the challenge_value if it is present.
Tests should match the style of the ones already there.

2025-01-06 02:21 UTC, birgelee commented on src/open_mpic_core/mpic_dcv_checker/mpic_dcv_checker.py
> +                    re_result = match.group(1)
@whtung If you are OK with it, I would be happy to make these changes and add the tests and push up a new edit

2025-01-06 05:42 UTC, whtung commented on src/open_mpic_core/mpic_dcv_checker/mpic_dcv_checker.py
> +                    re_result = match.group(1)
@birgelee Sure, thanks for your efforts again!!

2025-01-13 08:02 UTC, birgelee commented
to enable easy editing by project maintainers I made a branch in [whtung-main](https://github.com/open-mpic/open-mpic-core-python/tree/whtung-main) with these commits plus the proposed changes and tests. @sciros can you review PR#18 for merge in.

2025-01-17 03:11 UTC, merged

2025-01-17 03:18 UTC, sciros commented
@birgelee I thought we were gonna merge in the other branch...